colored output
# Conflicts:
#	scripts/env-nahlink
#	scripts/pull
#	scripts/pull-nahlink

diff --git a/scripts/pull b/scripts/pull
--- a/scripts/pull
+++ b/scripts/pull
@@ -107,12 +107,12 @@ do
             exit
             ;;
         \?)
-            echo "Invalid option: -$OPTARG" >&2
+            util::echo error "Invalid option: -$OPTARG" >&2
             usage
             exit 1
             ;;
         :)
-            echo "Option -$OPTARG requires an argument." >&2
+            util::echo error "Option -$OPTARG requires an argument." >&2
             exit 1
             ;;
     esac
@@ -130,7 +130,7 @@ src=$drush_alias_prefix.$src_env
 
 # environment
 if [[ -f $proj_dir/code ]]; then
-    echo "no code found at $proj_dir/code, did you run ./scripts/build?"
+    util::echo error "no code found at $proj_dir/code, did you run ./scripts/build?"
     exit 1
 fi
 
@@ -140,13 +140,13 @@ src_alias=$(drush-local sa "@$src" --format=json | jq '.["'"$src"'"]')
 list() {
     local src_envs
     src_envs=$(drush-local sa | grep -E "^@$drush_alias_prefix.[^.]+$" | sed "s/@$drush_alias_prefix\.//g")
-    echo src-alias values:
+    util::echo info "src-alias values:"
     echo "$src_envs"
     echo
 
     # ls will non-zero exit if pattern doesn't match
     set +e
-    echo database dumps:
+    util::echo info "database dumps:"
     ls -lh "$backup_dir/$backup_prefix.$drupal_multisite_id."*.sql.gz
     echo
     set -e
@@ -158,7 +158,7 @@ backup-drupal() {
     dumpfile_size=$(util::filesize "$backup_dir" "$backup_prefix.$drupal_multisite_id.local.*.sql.gz")
     drush sql-dump --structure-tables-list=cache,cache*,watchdog | \
         gzip -c | pv -s "$dumpfile_size" > "$dumpfile"
-    echo "wrote to $dumpfile"
+    util::echo info "wrote to $dumpfile"
 }
 
 pull-drupal() {
@@ -168,15 +168,15 @@ pull-drupal() {
         dumpfile_size=$(util::filesize "$backup_dir" "$backup_prefix.$drupal_multisite_id.$src_env.*.sql.gz")
         drush-local "@$src" sql-dump --structure-tables-list=cache,cache*,watchdog | \
             gzip -c | pv -s "$dumpfile_size" > "$dumpfile"
-        echo "wrote to $dumpfile"
+        util::echo info "wrote to $dumpfile"
     else
         dumpfile="$1"
-        echo "skipping source dump, using $1"
+        util::echo info "skipping source dump, using $1"
     fi
 
     drush -yq sql-drop
 
-    echo importing...
+    util::echo info "importing..."
     echo
     pv "$dumpfile" | gunzip -c | mysql-pipe
 }
@@ -251,7 +251,7 @@ pull-files-drupal() {
                 jq -r '."%paths"."%root" + "/" + ."%paths"."%files"')"
             jq='.[0].Mounts[] | select(.Destination == "/var/www_files/public") | .Source'
             dst=$(docker inspect "$container_id" | jq -r "$jq")
-            echo Trying to run rsync via sudo to write to container volume. You may be prompted for your password.
+            util::echo alert "Trying to run rsync via sudo to write to container volume. You may be prompted for your password."
             sudo rsync -e "ssh -i $ssh_id" \
                 -rLvz --size-only --ipv4 --progress --delete \
                 --exclude=/css \
@@ -265,7 +265,7 @@ pull-files-drupal() {
             src="$rsync_src:$(echo "$status" | jq -r '."%paths"."%private"')"
             jq='.[0].Mounts[] | select(.Destination == "/var/www_files/private") | .Source'
             dst=$(docker inspect "$container_id" | jq -r "$jq")
-            echo Trying to run rsync via sudo to write to container volume. You may be prompted for your password.
+            util::echo alert "Trying to run rsync via sudo to write to container volume. You may be prompted for your password."
             sudo rsync -e "ssh -i $ssh_id" \
                 -rLvz --size-only --ipv4 --progress --delete \
                 --exclude=/backup_migrate \
@@ -289,40 +289,40 @@ if [[ ! -z "$list" ]]; then
     exit 0
 fi
 
-echo source alias:
+util::echo info "source alias:"
 echo "$src_alias" | jq
 echo
 
 if [[ ! -z "$drupal_backup" ]]; then
-    echo backing up local drupal database
+    util::echo info "backing up local drupal database"
     echo
     backup-drupal
     echo
 fi
 
 if [[ ! -z "$drupal_pull" ]]; then
-    echo pulling drupal database
+    util::echo info "pulling drupal database"
     echo
     pull-drupal "$drupal_pull_dumpfile"
     echo
 fi
 
 if [[ ! -z $drupal_config ]]; then
-    echo drupal configure
+    util::echo info "drupal configure"
     echo
     configure-drupal "$drupal_config_update"
     echo
 fi
 
 if [[ ! -z $drupal_pull_files ]]; then
-    echo drupal files
+    util::echo info "drupal files"
     echo
     pull-files-drupal public
     echo
 fi
 
 if [[ ! -z $drupal_pull_private ]]; then
-    echo drupal private files
+    util::echo info "drupal private files"
     echo
     pull-files-drupal private
     echo
